/**
 * Product barcodes — the code only IDENTIFIES the product; price and stock
 * stay in the database (a price change never needs relabelling, and a
 * label can't be forged to pay less).
 */

/** EAN-13 check digit for the first 12 digits. */
export function ean13CheckDigit(first12: string): number {
  let sum = 0;
  for (let i = 0; i < 12; i++) sum += Number(first12[i]) * (i % 2 === 0 ? 1 : 3);
  return (10 - (sum % 10)) % 10;
}

export function isValidEan13(code: string): boolean {
  return /^\d{13}$/.test(code) && ean13CheckDigit(code.slice(0, 12)) === Number(code[12]);
}

/**
 * New in-store EAN-13 for a product without a manufacturer code. Prefix "2"
 * is the GS1 range reserved for in-store use, so it can never collide with
 * a real manufacturer code — and every scanner and camera reads EAN-13.
 */
export function generateInStoreEan13(): string {
  const digits = Array.from(crypto.getRandomValues(new Uint8Array(11)), (b) => String(b % 10)).join('');
  const first12 = '2' + digits;
  return first12 + ean13CheckDigit(first12);
}

/** A code generated by generateInStoreEan13 (needs a printed label), as
 *  opposed to a manufacturer code already printed on the packaging. */
export function isInStoreEan13(code: string): boolean {
  return code.startsWith('2') && isValidEan13(code);
}

/**
 * Hand-held scanners ("douchettes", USB or Bluetooth) behave as a keyboard:
 * they type the code very fast then press Enter. A human types far slower,
 * so a burst of keys a few ms apart ending with Enter is a scan — wherever
 * the focus is. Returns a stop function.
 */
export function listenForScannerBursts(onScan: (code: string) => void, opts: { maxGapMs?: number; minLength?: number } = {}) {
  const maxGap = opts.maxGapMs ?? 40;
  const minLength = opts.minLength ?? 4;
  let buffer = '';
  let last = 0;

  const onKeyDown = (e: KeyboardEvent) => {
    const now = performance.now();
    if (now - last > maxGap) buffer = ''; // too slow — a person typing, start over
    last = now;

    if (e.key === 'Enter') {
      if (buffer.length >= minLength) {
        const code = buffer;
        buffer = '';
        // Keep the scanner's Enter from also submitting whatever is focused.
        e.preventDefault();
        e.stopPropagation();
        onScan(code);
      }
      buffer = '';
      return;
    }
    if (e.key.length === 1) buffer += e.key;
  };

  window.addEventListener('keydown', onKeyDown, true);
  return () => window.removeEventListener('keydown', onKeyDown, true);
}

// ------------------------------------------------------------------
// Audible feedback — the cashier looks at the product, not the screen.
// Generated with WebAudio: no sound file to ship.
// ------------------------------------------------------------------
let audio: AudioContext | null = null;

function tone(freq: number, ms: number) {
  try {
    audio ??= new (window.AudioContext || (window as any).webkitAudioContext)();
    const osc = audio.createOscillator();
    const gain = audio.createGain();
    osc.frequency.value = freq;
    osc.type = 'square';
    gain.gain.value = 0.08;
    osc.connect(gain).connect(audio.destination);
    osc.start();
    osc.stop(audio.currentTime + ms / 1000);
  } catch { /* no audio — silent */ }
}

export function beepOk() {
  tone(1800, 90);
  try { navigator.vibrate?.(40); } catch { /* ignore */ }
}

export function beepError() {
  tone(300, 300);
  try { navigator.vibrate?.([80, 60, 80]); } catch { /* ignore */ }
}
